#include "BsaTest.h"

using namespace std;

INSTANTIATE_TEST_SUITE_P(
    FO4, BsaTest,
    testing::Values(tuple<const char*, const char*>{"fo4", "ccBGSFO4001-PipBoy(Black) - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4003-PipBoy(Camo01) - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4004-PipBoy(Camo02) - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4006-PipBoy(Chrome) - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4016-Prey - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4018-GaussRiflePrototype - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4019-ChineseStealthArmor - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4020-PowerArmorSkin(Black) - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4038-HorseArmor - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4044-HellfirePowerArmor - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4046-TesCan - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4096-AS_Enclave - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4110-WS_Enclave - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4115-X02 - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4116-HeavyFlamer - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFRSFO4001-HandmadeShotgun - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFSVFO4001-ModularMilitaryBackpack - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFSVFO4002-MidCenturyModern - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFSVFO4007-Halloween - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccOTMFO4001-Remnants - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccSBJFO4003-Grenade - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCCoast - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCCoast - Voices_en.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCNukaWorld - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCNukaWorld - Voices_en.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCRobot - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCRobot - Voices_en.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCworkshop01 - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCworkshop02 - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCworkshop03 - Main.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCworkshop03 - Voices_en.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Animations.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Interface.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Materials.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Meshes.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - MeshesExtra.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Misc.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Nvflex.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Shaders.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Sounds.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Startup.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Voices.ba2"}));

INSTANTIATE_TEST_SUITE_P(
    FO4Textures, BsaTest,
    testing::Values(tuple<const char*, const char*>{"fo4", "ccBGSFO4001-PipBoy(Black) - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4003-PipBoy(Camo01) - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4004-PipBoy(Camo02) - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4006-PipBoy(Chrome) - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4016-Prey - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4018-GaussRiflePrototype - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4019-ChineseStealthArmor - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4020-PowerArmorSkin(Black) - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4038-HorseArmor - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4044-HellfirePowerArmor - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4046-TesCan - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4096-AS_Enclave - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4110-WS_Enclave - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4115-X02 - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccBGSFO4116-HeavyFlamer - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFRSFO4001-HandmadeShotgun - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFSVFO4001-ModularMilitaryBackpack - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFSVFO4002-MidCenturyModern - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccFSVFO4007-Halloween - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccOTMFO4001-Remnants - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "ccSBJFO4003-Grenade - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCCoast - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCNukaWorld - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCRobot - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCworkshop01 - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCworkshop02 - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "DLCworkshop03 - Textures.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures1.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures2.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures3.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures4.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures5.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures6.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures7.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures8.ba2"},
                    tuple<const char*, const char*>{"fo4", "Fallout4 - Textures9.ba2"}));
